export const CREATE_FRIEND_REQUEST_REQUEST = "CREATE_FRIEND_REQUEST_REQUEST";
export const CREATE_FRIEND_REQUEST_SUCCESS = "CREATE_FRIEND_REQUEST_SUCCESS";
export const CREATE_FRIEND_REQUEST_FAIL = "CREATE_FRIEND_REQUEST_FAIL";
export const CREATE_FRIEND_REQUEST_RESET = "CREATE_FRIEND_REQUEST_RESET";

export const FRIEND_REQUESTS_REQUEST = "FRIEND_REQUESTS_REQUEST";
export const FRIEND_REQUESTS_SUCCESS = "FRIEND_REQUESTS_SUCCESS";
export const FRIEND_REQUESTS_FAIL = "FRIEND_REQUESTS_FAIL";
export const FRIEND_REQUESTS_RESET = "FRIEND_REQUESTS_RESET";

export const SENT_FRIEND_REQUESTS_REQUEST = "SENT_FRIEND_REQUESTS_REQUEST";
export const SENT_FRIEND_REQUESTS_SUCCESS = "SENT_FRIEND_REQUESTS_SUCCESS";
export const SENT_FRIEND_REQUESTS_FAIL = "SENT_FRIEND_REQUESTS_FAIL";
export const SENT_FRIEND_REQUESTS_RESET = "SENT_FRIEND_REQUESTS_RESET";

export const RESPOND_FRIEND_REQUEST_REQUEST = "RESPOND_FRIEND_REQUEST_REQUEST";
export const RESPOND_FRIEND_REQUEST_SUCCESS = "RESPOND_FRIEND_REQUEST_SUCCESS";
export const RESPOND_FRIEND_REQUEST_FAIL = "RESPOND_FRIEND_REQUEST_FAIL";
