export const USER_LISTS_REQUEST = "USER_LISTS_REQUEST";
export const USER_LISTS_SUCCESS = "USER_LISTS_SUCCESS";
export const USER_LISTS_FAIL = "USER_LISTS_FAIL";
export const USER_LISTS_RESET = "USER_LISTS_RESET";

export const SHARED_LISTS_REQUEST = "SHARED_LISTS_REQUEST";
export const SHARED_LISTS_SUCCESS = "SHARED_LISTS_SUCCESS";
export const SHARED_LISTS_FAIL = "SHARED_LISTS_FAIL";
export const SHARED_LISTS_RESET = "SHARED_LISTS_RESET";

export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST";
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL";
export const CREATE_LIST_RESET = "CREATE_LIST_RESET";
