export const CREATE_LIST_ITEM_REQUEST = "CREATE_LIST_ITEM_REQUEST";
export const CREATE_LIST_ITEM_SUCCESS = "CREATE_LIST_ITEM_SUCCESS";
export const CREATE_LIST_ITEM_FAIL = "CREATE_LIST_ITEM_FAIL";
export const CREATE_LIST_ITEM_RESET = "CREATE_LIST_ITEM_RESET";

export const LIST_ITEMS_REQUEST = "LIST_ITEMS_REQUEST";
export const LIST_ITEMS_SUCCESS = "LIST_ITEMS_SUCCESS";
export const LIST_ITEMS_FAIL = "LIST_ITEMS_FAIL";
export const LIST_ITEMS_UPDATE = "LIST_ITEMS_UPDATE";
export const LIST_ITEMS_RESET = "LIST_ITEMS_RESET";

export const COMPLETE_LIST_ITEM_REQUEST = "COMPLETE_LIST_ITEM_REQUEST";
export const COMPLETE_LIST_ITEM_SUCCESS = "COMPLETE_LIST_ITEM_SUCCESS";
export const COMPLETE_LIST_ITEM_FAIL = "COMPLETE_LIST_ITEM_FAIL";
export const COMPLETE_LIST_ITEM_RESET = "COMPLETE_LIST_ITEM_RESET";

export const DELETE_LIST_ITEM_REQUEST = "DELETE_LIST_ITEM_REQUEST";
export const DELETE_LIST_ITEM_SUCCESS = "DELETE_LIST_ITEM_SUCCESS";
export const DELETE_LIST_ITEM_FAIL = "DELETE_LIST_ITEM_FAIL";
export const DELETE_LIST_ITEM_RESET = "DELETE_LIST_ITEM_RESET";

export const CREATE_LIST_SUB_ITEM_REQUEST = "CREATE_LIST_SUB_ITEM_REQUEST";
export const CREATE_LIST_SUB_ITEM_SUCCESS = "CREATE_LIST_SUB_ITEM_SUCCESS";
export const CREATE_LIST_SUB_ITEM_FAIL = "CREATE_LIST_SUB_ITEM_FAIL";
export const CREATE_LIST_SUB_ITEM_RESET = "CREATE_LIST_SUB_ITEM_RESET";

export const COMPLETE_LIST_SUB_ITEM_REQUEST = "COMPLETE_LIST_SUB_ITEM_REQUEST";
export const COMPLETE_LIST_SUB_ITEM_SUCCESS = "COMPLETE_LIST_SUB_ITEM_SUCCESS";
export const COMPLETE_LIST_SUB_ITEM_FAIL = "COMPLETE_LIST_SUB_ITEM_FAIL";
export const COMPLETE_LIST_SUB_ITEM_RESET = "COMPLETE_LIST_SUB_ITEM_RESET";

export const DELETE_LIST_SUB_ITEM_REQUEST = "DELETE_LIST_SUB_ITEM_REQUEST";
export const DELETE_LIST_SUB_ITEM_SUCCESS = "DELETE_LIST_SUB_ITEM_SUCCESS";
export const DELETE_LIST_SUB_ITEM_FAIL = "DELETE_LIST_SUB_ITEM_FAIL";
export const DELETE_LIST_SUB_ITEM_RESET = "DELETE_LIST_SUB_ITEM_RESET";
