export const CREATE_LIST_ITEM_REQUEST = "CREATE_LIST_ITEM_REQUEST";
export const CREATE_LIST_ITEM_SUCCESS = "CREATE_LIST_ITEM_SUCCESS";
export const CREATE_LIST_ITEM_FAIL = "CREATE_LIST_ITEM_FAIL";
export const CREATE_LIST_ITEM_RESET = "CREATE_LIST_ITEM_RESET";

export const GET_LIST_ITEMS_REQUEST = "GET_LIST_ITEMS_REQUEST";
export const GET_LIST_ITEMS_SUCCESS = "GET_LIST_ITEMS_SUCCESS";
export const GET_LIST_ITEMS_FAIL = "GET_LIST_ITEMS_FAIL";
export const GET_LIST_ITEMS_RESET = "GET_LIST_ITEMS_RESET";
