export const USER_LISTS_REQUEST = "USER_LISTS_REQUEST";
export const USER_LISTS_SUCCESS = "USER_LISTS_SUCCESS";
export const USER_LISTS_FAIL = "USER_LISTS_FAIL";

export const SHARED_LISTS_REQUEST = "SHARED_LISTS_REQUEST";
export const SHARED_LISTS_SUCCESS = "SHARED_LISTS_SUCCESS";
export const SHARED_LISTS_FAIL = "SHARED_LISTS_FAIL";
