export const CREATE_SHARE_REQUEST_REQUEST = "CREATE_SHARE_REQUEST_REQUEST";
export const CREATE_SHARE_REQUEST_SUCCESS = "CREATE_SHARE_REQUEST_SUCCESS";
export const CREATE_SHARE_REQUEST_FAIL = "CREATE_SHARE_REQUEST_FAIL";
export const CREATE_SHARE_REQUEST_RESET = "CREATE_SHARE_REQUEST_RESET";

export const GET_SHARE_REQUESTS_REQUEST = "GET_SHARE_REQUESTS_REQUEST";
export const GET_SHARE_REQUESTS_SUCCESS = "GET_SHARE_REQUESTS_SUCCESS";
export const GET_SHARE_REQUESTS_FAIL = "GET_SHARE_REQUESTS_FAIL";

export const GET_SENT_SHARE_REQUESTS_REQUEST =
  "GET_SENT_SHARE_REQUESTS_REQUEST";
export const GET_SENT_SHARE_REQUESTS_SUCCESS =
  "GET_SENT_SHARE_REQUESTS_SUCCESS";
export const GET_SENT_SHARE_REQUESTS_FAIL = "GET_SENT_SHARE_REQUESTS_FAIL";
