export const CREATE_SHARE_REQUEST_REQUEST = "CREATE_SHARE_REQUEST_REQUEST";
export const CREATE_SHARE_REQUEST_SUCCESS = "CREATE_SHARE_REQUEST_SUCCESS";
export const CREATE_SHARE_REQUEST_FAIL = "CREATE_SHARE_REQUEST_FAIL";
export const CREATE_SHARE_REQUEST_RESET = "CREATE_SHARE_REQUEST_RESET";

export const SHARE_REQUESTS_REQUEST = "SHARE_REQUESTS_REQUEST";
export const SHARE_REQUESTS_SUCCESS = "SHARE_REQUESTS_SUCCESS";
export const SHARE_REQUESTS_FAIL = "SHARE_REQUESTS_FAIL";
export const SHARE_REQUESTS_RESET = "SHARE_REQUESTS_RESET";

export const SENT_SHARE_REQUESTS_REQUEST = "SENT_SHARE_REQUESTS_REQUEST";
export const SENT_SHARE_REQUESTS_SUCCESS = "SENT_SHARE_REQUESTS_SUCCESS";
export const SENT_SHARE_REQUESTS_FAIL = "SENT_SHARE_REQUESTS_FAIL";
export const SENT_SHARE_REQUESTS_RESET = "SENT_SHARE_REQUESTS_RESET";

export const RESPOND_SHARE_REQUEST_REQUEST = "RESPOND_SHARE_REQUEST_REQUEST";
export const RESPOND_SHARE_REQUEST_SUCCESS = "RESPOND_SHARE_REQUEST_SUCCESS";
export const RESPOND_SHARE_REQUEST_FAIL = "RESPOND_SHARE_REQUEST_FAIL";
