export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_FRIENDLIST_REQUEST = "USER_FRIENDLIST_REQUEST";
export const USER_FRIENDLIST_SUCCESS = "USER_FRIENDLIST_SUCCESS";
export const USER_FRIENDLIST_FAIL = "USER_FRIENDLIST_FAIL";
export const USER_FRIENDLIST_RESET = "USER_FRIENDLIST_RESET";

export const USER_FRIEND_ADD_REQUEST = "USER_FRIEND_ADD_REQUEST";
export const USER_FRIEND_ADD_SUCCESS = "USER_FRIEND_ADD_SUCCESS";
export const USER_FRIEND_ADD_FAIL = "USER_FRIEND_ADD_FAIL";
export const USER_FRIEND_ADD_RESET = "USER_FRIEND_ADD_RESET";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAIL = "USER_SEARCH_FAIL";
export const USER_SEARCH_RESET = "USER_SEARCH_RESET";
